### PR TITLE
build: integrate whiskers

### PR DESCRIPTION
**Pull request by nullishamy**
`lightColors` seemed to be the exact same port-wide, with the exception of accents. Lighten % closely guessed @ 75% for accents.

### CODE REVIEW

**Review by jayylmao — APPROVED** [review]
sorry, just got to this now. looks good. i'll merge it.

**Comment by nullishamy** [comment]
Just noticed this got merged. Is `lightColors` being the way it is correct? It seems wrong?

**Comment by jayylmao** [comment]
as in, the fact that `lightColors` is exactly the same throughout the port? yeah.

**Comment by nullishamy** [comment]
> as in, the fact that `lightColors` is exactly the same throughout the port? yeah.

Yes, that is what I was referring to. Is it wrong?

**Comment by jayylmao** [comment]
sorry for the confusion, it's intended to be the same throughout the port.

**Pull request merged**
